name: network
description: A new Flutter package.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  #dio: ^3.0.10
  #dio: ^4.0.0-prev3

  dio: ^4.0.0
  package_info: ^2.0.0
  dio_http2_adapter: ^2.0.0
  data_connection_checker: ^0.3.4
  retrofit: any
  logger: any
  json_annotation: any

  connectivity: ^3.0.2
  core:
    path: ../core


dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  json_serializable: any


flutter:

